# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# 26.x is unobfuscated - disable remapping
fabric.loom.disableObfuscation=true

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.12

# Mod Properties
mod_version=1.4.0
maven_group=com.example

# Dependencies
fabric_api_version=0.152.1+26.1.2
cloth_config_version=26.1.154
modmenu_version=18.0.0-beta.1
