package com.npctranslator.config;

import com.npctranslator.NPCTranslatorClient;
import com.terraformersmc.modmenu.api.ConfigScreenFactory;
import com.terraformersmc.modmenu.api.ModMenuApi;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.gui.screen.option.KeybindsScreen;
import net.minecraft.text.Text;

import java.awt.*;

@Environment(EnvType.CLIENT)
public class ModMenuIntegration implements ModMenuApi {

    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
        return this::buildScreen;
    }

    private Screen buildScreen(Screen parent) {
        ModConfig config = ModConfig.INSTANCE;

        return YetAnotherConfigLib.createBuilder()
                .title(Text.translatable("text.autoconfig.npc_translator.title"))
                .save(() -> {
                    ModConfig.save();
                    NPCTranslatorClient.reloadConfig();
                })
                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("category.npctranslator.general"))
                        .tooltip(Text.literal("General Settings"))
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("General"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.enabled"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.enabled.tooltip")))
                                        .binding(true, () -> config.enabled, val -> config.enabled = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.useGameLanguage"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.useGameLanguage.tooltip")))
                                        .binding(true, () -> config.useGameLanguage, val -> config.useGameLanguage = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<ModConfig.TranslationLanguage>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.targetLanguage"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.targetLanguage.tooltip")))
                                        .binding(ModConfig.TranslationLanguage.TURKISH, () -> config.targetLanguage, val -> config.targetLanguage = val)
                                        .controller(opt -> EnumControllerBuilder.create(opt).enumClass(ModConfig.TranslationLanguage.class))
                                        .build())
                                .option(ButtonOption.createBuilder()
                                        .name(Text.translatable("npctranslator.config.keybinds.name"))
                                        .description(OptionDescription.of(Text.translatable("npctranslator.config.keybinds.desc")))
                                        .action((screen, button) -> {
                                            MinecraftClient.getInstance().setScreen(new KeybindsScreen(screen, MinecraftClient.getInstance().options));
                                        })
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Active Translators"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.enableGoogleItem"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.enableGoogleItem.tooltip")))
                                        .binding(true, () -> config.enableGoogleItem, val -> config.enableGoogleItem = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.enableGeminiItem"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.enableGeminiItem.tooltip")))
                                        .binding(true, () -> config.enableGeminiItem, val -> config.enableGeminiItem = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.enableGroqItem"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.enableGroqItem.tooltip")))
                                        .binding(true, () -> config.enableGroqItem, val -> config.enableGroqItem = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.enableMistralItem"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.enableMistralItem.tooltip")))
                                        .binding(true, () -> config.enableMistralItem, val -> config.enableMistralItem = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.enableOpenRouterItem"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.enableOpenRouterItem.tooltip")))
                                        .binding(true, () -> config.enableOpenRouterItem, val -> config.enableOpenRouterItem = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("category.npctranslator.api"))
                        .tooltip(Text.literal("API Settings"))
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Groq AI"))
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.groqApiKey"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.groqApiKey.tooltip")))
                                        .binding("", () -> config.groqApiKey, val -> config.groqApiKey = val)
                                        .controller(StringControllerBuilder::create)
                                        .build())
                                .option(Option.<ModConfig.GroqModel>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.groqModel"))
                                        .binding(ModConfig.GroqModel.LLAMA_3_3_70B, () -> config.groqModel, val -> config.groqModel = val)
                                        .controller(opt -> EnumControllerBuilder.create(opt).enumClass(ModConfig.GroqModel.class))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Gemini AI"))
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.geminiApiKey"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.geminiApiKey.tooltip")))
                                        .binding("", () -> config.geminiApiKey, val -> config.geminiApiKey = val)
                                        .controller(StringControllerBuilder::create)
                                        .build())
                                .option(Option.<ModConfig.GeminiModel>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.geminiModel"))
                                        .binding(ModConfig.GeminiModel.GEMINI_2_5_FLASH, () -> config.geminiModel, val -> config.geminiModel = val)
                                        .controller(opt -> EnumControllerBuilder.create(opt).enumClass(ModConfig.GeminiModel.class))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("text.autoconfig.npc_translator.group.mistral"))
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.mistralApiKey"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.mistralApiKey.tooltip")))
                                        .binding("", () -> config.mistralApiKey, val -> config.mistralApiKey = val)
                                        .controller(StringControllerBuilder::create)
                                        .build())
                                .option(Option.<ModConfig.MistralModel>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.mistralModel"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.mistralModel.tooltip")))
                                        .binding(ModConfig.MistralModel.MISTRAL_LARGE_2512, () -> config.mistralModel, val -> config.mistralModel = val)
                                        .controller(opt -> EnumControllerBuilder.create(opt)
                                                .enumClass(ModConfig.MistralModel.class)
                                                .formatValue(val -> Text.literal(val.toString())))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("text.autoconfig.npc_translator.group.openrouter"))
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.openRouterApiKey"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.openRouterApiKey.tooltip")))
                                        .binding("", () -> config.openRouterApiKey, val -> config.openRouterApiKey = val)
                                        .controller(StringControllerBuilder::create)
                                        .build())
                                .option(Option.<ModConfig.OpenRouterModel>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.openRouterModel"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.openRouterModel.tooltip")))
                                        .binding(ModConfig.OpenRouterModel.OPENROUTER_FREE, () -> config.openRouterModel, val -> config.openRouterModel = val)
                                        .controller(opt -> EnumControllerBuilder.create(opt)
                                                .enumClass(ModConfig.OpenRouterModel.class)
                                                .formatValue(val -> Text.literal(val.toString())))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Other Settings"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.autoFallbackOnLimit"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.autoFallbackOnLimit.tooltip")))
                                        .binding(true, () -> config.autoFallbackOnLimit, val -> config.autoFallbackOnLimit = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("category.npctranslator.chat"))
                        .tooltip(Text.literal("Chat Translation Settings"))
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Chat Translation"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.autoTranslateChat"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.autoTranslateChat.tooltip")))
                                        .binding(false, () -> config.autoTranslateChat, val -> config.autoTranslateChat = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.onlyTranslateNpcChat"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.onlyTranslateNpcChat.tooltip")))
                                        .binding(true, () -> config.onlyTranslateNpcChat, val -> config.onlyTranslateNpcChat = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.<ModConfig.TranslationProvider>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.translationProvider"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.translationProvider.tooltip")))
                                        .binding(ModConfig.TranslationProvider.GOOGLE, () -> config.chatTranslationProvider, val -> config.chatTranslationProvider = val)
                                        .controller(opt -> EnumControllerBuilder.create(opt).enumClass(ModConfig.TranslationProvider.class))
                                        .build())
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("category.npctranslator.item"))
                        .tooltip(Text.literal("Item Tooltip Translation Settings"))
                        .group(OptionGroup.createBuilder()
                                .name(Text.literal("Item Translation"))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("text.autoconfig.npc_translator.option.autoTranslateItems"))
                                        .description(OptionDescription.of(Text.translatable("text.autoconfig.npc_translator.option.autoTranslateItems.tooltip")))
                                        .binding(false, () -> config.autoTranslateItems, val -> config.autoTranslateItems = val)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .build())
                .build()
                .generateScreen(parent);
    }
}
